server:
  port: 80
spring:
  application:
    name: cloud-order-ribbon80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true