server:
  port: 8001
spring:
  application:
    name: payment-feign-hystrix
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zimu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment-hystrix8001
    prefer-ip-address: true