server:
  port: 80
spring:
  application:
    name: order-hystrix80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true

#开启feign支持熔断机制
feign:
  hystrix:
    enabled: true
